services:
  - type: web
    name: seizure-sentinel
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
